### ISSUE TITLE
sketches and idea concept from the development team

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#1]

**Comment by veir0004** [comment]
![aawh-jpg](https://cloud.githubusercontent.com/assets/6371777/5710972/e872c3e6-9a74-11e4-8051-20fd607b8626.jpg)

**Comment by veir0004** [comment]
![look2](https://cloud.githubusercontent.com/assets/6371777/5711067/ae037858-9a75-11e4-85bb-41ed4f7b4ee0.jpg)
![look-2](https://cloud.githubusercontent.com/assets/6371777/5711069/af9d5634-9a75-11e4-9e73-b4655e45078c.jpg)

**Comment by joeyanhhuynh** [comment]
![moodboard_page_1](https://cloud.githubusercontent.com/assets/6371782/5711289/3333a09c-9a77-11e4-8092-432a3ca79e31.jpg)
![moodboard_page_2](https://cloud.githubusercontent.com/assets/6371782/5711288/3330ef1e-9a77-11e4-8075-f53b65c23e53.jpg)

**Comment by joeyanhhuynh** [comment]
![scan 6](https://cloud.githubusercontent.com/assets/6371782/5711844/99f195ec-9a7b-11e4-9566-c4f9bee47b65.jpeg)
![scan 7](https://cloud.githubusercontent.com/assets/6371782/5711843/99ed07d4-9a7b-11e4-87c8-7b0004c7c17e.jpeg)
