### ISSUE TITLE
Completed style tiles

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#10]
Include a high fidelity mockup of header and footer for both mobile and desktop

**Comment by veir0004** [comment]
![style-tile-01](https://cloud.githubusercontent.com/assets/6371777/5904749/da2a2a06-a558-11e4-8ae5-4ec1d97c1f7b.jpg)
![style-tile-02](https://cloud.githubusercontent.com/assets/6371777/5904750/da3101aa-a558-11e4-8809-9839d211905f.jpg)

**Comment by veir0004** [comment]
![header-footer-nav-03](https://cloud.githubusercontent.com/assets/6371777/5907932/149a9438-a571-11e4-82ab-adc06dc53e9b.jpg)

**Comment by veir0004** [comment]
![header-footer-nav-03-03-03](https://cloud.githubusercontent.com/assets/6371777/5908019/d173c5ca-a571-11e4-8ac3-648c882bb496.jpg)

**Comment by veir0004** [comment]
![header-footer-2](https://cloud.githubusercontent.com/assets/6371777/6014724/7ebf2f06-ab37-11e4-8a81-7172242cb88b.jpg)

@joeyanhhuynh
