### ISSUE TITLE
Update wireframes 

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#11]
Update wireframes based on usability testing.

**Comment by veir0004** [comment]
![update-wireframe1-01](https://cloud.githubusercontent.com/assets/6371777/5903721/58700fe6-a551-11e4-9f9b-667f6cd78db7.jpg)
![update-wireframe1-02](https://cloud.githubusercontent.com/assets/6371777/5903720/586da490-a551-11e4-81f5-70f29007f89c.jpg)
