### ISSUE TITLE
Export images and icons 

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#16]
Export all assets needed for the Development Team (logo, svg icons, images, etc.) in the appropriate web formats

**Comment by veir0004** [comment]
https://www.dropbox.com/s/vkngztjcn338ggq/image%202.zip?dl=0

![aawh-icons](https://cloud.githubusercontent.com/assets/6371777/5996478/607e8916-aa78-11e4-9ebd-0993efc2cd03.jpg)
