### ISSUE TITLE
Sketches, idea concepts and inspiration

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#2]

**Comment by veir0004** [comment]
![look1](https://cloud.githubusercontent.com/assets/6371777/5711123/0af9337c-9a76-11e4-84d1-18d9d455a80f.jpg)
![look-1](https://cloud.githubusercontent.com/assets/6371777/5711124/0cce847c-9a76-11e4-8cc9-40e52a67a5d6.jpg)

**Comment by veir0004** [comment]
![look2](https://cloud.githubusercontent.com/assets/6371777/5711126/118c4cc4-9a76-11e4-8eb0-1ceb4e1aaaa0.jpg)
![look-2](https://cloud.githubusercontent.com/assets/6371777/5711127/131b25ce-9a76-11e4-9d61-877afab0fefa.jpg)
