### ISSUE TITLE
Export images / SVG graphics

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#24]
All images / SVG graphics should be saved for web, and added to the images folder.

**Comment by veir0004** [comment]
https://www.dropbox.com/s/vmgpi9vxffguxz8/images-billboard.zip?dl=0

@joeyanhhuynh  let me know if you need any thing else regarding the images

**Comment by veir0004** [comment]
@joeyanhhuynh i uploaded the square images on github but im not sure if it worked so here is the link just as back up https://www.dropbox.com/s/76ag3ysaieuyfhf/images-square%202.zip?dl=0
