### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#3]
Personas of the website

**Comment by joeyanhhuynh** [comment]
![scan 3](https://cloud.githubusercontent.com/assets/6371782/5711825/6e50cf52-9a7b-11e4-848c-538693500f11.jpeg)
![scan 4](https://cloud.githubusercontent.com/assets/6371782/5711826/6e51c92a-9a7b-11e4-9258-38f822087286.jpeg)
![scan 5](https://cloud.githubusercontent.com/assets/6371782/5711824/6e4fc580-9a7b-11e4-8bec-e8d4c3242038.jpeg)
