### ISSUE TITLE
Information architecture breakdown and analysis, sitemap of the website

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#6]

**Comment by joeyanhhuynh** [comment]
![site_map](https://cloud.githubusercontent.com/assets/6371782/5796147/6b9409de-9f6f-11e4-94ba-8e1570d0d8a3.jpg)

**Comment by joeyanhhuynh** [comment]
![site_map](https://cloud.githubusercontent.com/assets/6371782/5806221/3933d494-9fe5-11e4-8db7-2135d1ff275d.jpg)
