### ISSUE TITLE
Gathering of site content.

### ISSUE THREAD

**Issue by mBluebear** [mBluebear/actionagainsthunger#7]
Put in all the info needed and take out all the unnecessary content.

**Comment by joeyanhhuynh** [comment]
*\* Put a search button on the navigation.
Home page:

Carousel (3-5 feature stories); reduce the width of the carousel.
Description: Action Hunger
Put a donate button on every page.
Add the big impact number back to the main page to pursue user to donate.
Mission
Countries map
About Page:

Keep all the information.
*\* Take out the Hunger page

Impact page:
1. Nutrition
2. Water, Santitation & Hygiene
3. Food Security & Livelihoods
4. Emergency Response

Stories (Blog):

Keep all the information.
Take Action:

Make donate
Fundraise
Give Monthly
Buy life saving gift *\* More giving options
